name: Nombre_Workflow

on:
    push:
        branches:
        - master
jobs:
    Nombre_Trabajo:
        runs-on: ubuntu-18.04
        steps:
        - name: Echo the message
          run: echo "hola mundo"