name: Say hello

on:
    push:
        branches:
        - master
jobs:
    hello_woild:
            runs-on: ubuntu-18.04
            steps:
            - name: Echo the message
              run: echo "hola mundo"