name: Nombre_Workflow

on:
    push:
        branches:
        - master
jobs:
    Nombre_Trabajo:
        runs-on: ubuntu-20.04
        steps:
        - name: Echo the message
          run: echo "hola mundo"
        - name: Echo the message
          run: date
        - run: ls -l