name: Nombre_Workflow_Deployment_Pipeline

on:
    push:
        branches:
        - master
jobs:
    Nombre_Trabajo:
        runs-on: ubuntu-20.04
        steps:
        - name: Mostrar mensaje
          run: echo "Iniciando.."
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install dependencies
          run: npm install
        - name: Lint
          run: npm run eslint

       