name: Nombre_Workflow_Deployment_Pipeline

on:
    push:
        branches:
        - master #se puede dejar de cualquiera de las dos forma [master] o - master
    pull_request:
      branches: [master]
      types: [opened, synchronize]


jobs:
    Nombre_Trabajo:
        runs-on: ubuntu-20.04
        steps:
        - name: Mostrar mensaje
          run: echo "Iniciando.."
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: actions/setup-node@v3
          with:
            node-version: 16
        - name: Install dependencies
          run: npm ci         
        - name: Lint
          run: npm run eslint        
        - name: Build
          run: npm run build
        - name: Test
          run: npm run test        
        #- name: E2E tests
        #  uses: cypress-io/github-action@v5
        #  with:
        #    command: npm run test:e2e
        #    start: npm run start-test
        #    wait-on: http://localhost:5000
        - name: Deploy secrets
          if: ${{ github.event_name == 'push' }}
          run: echo ${{secrets.HEROKU_API_KEY}}     
          #uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
          #with:
            #heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            #heroku_app_name: ${{secrets.HEROKU_APP}}
            #heroku_email: ${{secrets.HEROKU_EMAIL}}
            #healthcheck: "http://${{secrets.HEROKU_APP}}/health"
            #rollbackonhealthcheckfailed: true


       