name: Nombre_Workflow_Deployment_Pipeline

on:
    push:
        branches:
        - master #se puede dejar de cualquiera de las dos forma [master] o - master
    pull_request:
      branches: [master]
      types: [opened, synchronize]


jobs:

    Trabajo_2:
        runs-on: ubuntu-20.04
        steps:
        - name: Cancelar construcciones al tiempo
          uses: styfle/cancel-workflow-action@0.9.1
          with:
            access_token: ${{ github.token }}

    lint:
      runs-on: ubuntu-20.04
      steps:
        - name: Mostrar mensaje Lint
          run: echo "Iniciando Lint.."
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: actions/setup-node@v3
          with:
            node-version: 16
        - name: Install dependencies
          run: npm ci         
        - name: Lint
          run: npm run eslint

    build:
      runs-on: ubuntu-20.04
      steps:        
      - name: Mostrar mensaje Build
        run: echo "Iniciando Build.."
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci           
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist #carpeta dist

    test:
      needs: [lint, build]
      runs-on: ubuntu-20.04
      steps:        
      - name: Mostrar mensaje Test
        run: echo "Iniciando Test.."
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist #carpeta dist
      - name: Test
        run: npm run test  


    e2e:
      needs: [lint, build]
      runs-on: ubuntu-20.04
      steps:        
      - name: Mostrar mensaje E2E
        run: echo "Iniciando E2E.."
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist #carpeta dist       
      - name: E2E tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-test
          wait-on: http://localhost:5000


    deploy:
        needs: [test, e2e]
        runs-on: ubuntu-20.04
        steps:        
        - name: Mostrar mensaje Deploy
          run: echo "Iniciando Deploy.."
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0      
        - name: Deploy secrets
          if: ${{ github.event_name == 'push' }}
          run: echo ${{secrets.HEROKU_API_KEY}}     
          #uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
          #with:
            #heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            #heroku_app_name: ${{secrets.HEROKU_APP}}
            #heroku_email: ${{secrets.HEROKU_EMAIL}}
            #healthcheck: "http://${{secrets.HEROKU_APP}}/health"
            #rollbackonhealthcheckfailed: true


       